-- The Royal Cakes / Cafe Càtta - PostgreSQL (Supabase)
-- Run this in Supabase SQL Editor.
-- Safe for an existing project: adds missing columns before seeding.

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    category VARCHAR(80) DEFAULT 'Other',
    price NUMERIC(10,2) NOT NULL,
    image VARCHAR(500),
    is_available BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    total_amount NUMERIC(10,2) NOT NULL,
    status VARCHAR(50) DEFAULT 'Placed',
    customer_phone VARCHAR(30),
    order_type VARCHAR(20) DEFAULT 'pickup',
    delivery_address TEXT,
    payment_method VARCHAR(30) DEFAULT 'pay_at_cafe',
    payment_status VARCHAR(30) DEFAULT 'Unpaid',
    notes TEXT,
    razorpay_order_id VARCHAR(100),
    razorpay_payment_id VARCHAR(100),
    razorpay_signature VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    subtotal NUMERIC(10,2) NOT NULL
);

-- Migrations for databases created with the earlier version.
ALTER TABLE products ADD COLUMN IF NOT EXISTS category VARCHAR(80) DEFAULT 'Other';
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_available BOOLEAN DEFAULT TRUE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(30);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_type VARCHAR(20) DEFAULT 'pickup';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_address TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(30) DEFAULT 'pay_at_cafe';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status VARCHAR(30) DEFAULT 'Unpaid';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS razorpay_order_id VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS razorpay_payment_id VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS razorpay_signature VARCHAR(255);

UPDATE products SET category = 'Cakes' WHERE category IS NULL OR category = '';
UPDATE products SET is_available = TRUE WHERE is_available IS NULL;
UPDATE orders SET order_type = 'pickup' WHERE order_type IS NULL;
UPDATE orders SET payment_method = 'pay_at_cafe' WHERE payment_method IS NULL;
UPDATE orders SET payment_status = 'Unpaid' WHERE payment_status IS NULL;

CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_available ON products(is_available);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);

-- Seed products only when the table is empty.
INSERT INTO products (name, description, category, price, image, is_available)
SELECT * FROM (VALUES
    ('Chocolate Truffle Cake', 'Rich chocolate cake with smooth truffle frosting.', 'Cakes', 599.00, 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=900&q=80', TRUE),
    ('yummy Red Velvet Cake', 'Soft red velvet sponge with cream cheese frosting.', 'Cakes', 649.00, 'https://images.unsplash.com/photo-1586788224331-947f68671cf1?w=900&q=80', TRUE),
    ('Black Forest Cake', 'Classic chocolate sponge with cherries and cream.', 'Cakes', 549.00, 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=900&q=80', TRUE),
    ('Butterscotch Cake', 'Creamy butterscotch cake with caramel crunch.', 'Cakes', 499.00, 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=900&q=80', TRUE)
) AS seed(name, description, category, price, image, is_available)
WHERE NOT EXISTS (SELECT 1 FROM products);

-- To make an existing account an admin, run separately:
-- UPDATE users SET is_admin = TRUE WHERE email = 'YOUR_ADMIN_EMAIL';
